// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClhDeVDy96ZqOXW23z6F__Kleq8OcXjUo',
    appId: '1:424244082829:web:b91a2b80a9bf08dbbb8ac4',
    messagingSenderId: '424244082829',
    projectId: 'pingolearn-18bf2',
    authDomain: 'pingolearn-18bf2.firebaseapp.com',
    storageBucket: 'pingolearn-18bf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAonZoTyBgQNPj89VI0Zm-jeKHy_Fx96s',
    appId: '1:424244082829:android:7538b3ded3e9d895bb8ac4',
    messagingSenderId: '424244082829',
    projectId: 'pingolearn-18bf2',
    storageBucket: 'pingolearn-18bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGKk-Pjn2X2F7gduSbjbEUwEHoFeWi4o',
    appId: '1:424244082829:ios:e2d9a40a9066e302bb8ac4',
    messagingSenderId: '424244082829',
    projectId: 'pingolearn-18bf2',
    storageBucket: 'pingolearn-18bf2.appspot.com',
    iosBundleId: 'com.example.pingoLearnAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvGKk-Pjn2X2F7gduSbjbEUwEHoFeWi4o',
    appId: '1:424244082829:ios:e2d9a40a9066e302bb8ac4',
    messagingSenderId: '424244082829',
    projectId: 'pingolearn-18bf2',
    storageBucket: 'pingolearn-18bf2.appspot.com',
    iosBundleId: 'com.example.pingoLearnAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClhDeVDy96ZqOXW23z6F__Kleq8OcXjUo',
    appId: '1:424244082829:web:29b24bc2fbd21451bb8ac4',
    messagingSenderId: '424244082829',
    projectId: 'pingolearn-18bf2',
    authDomain: 'pingolearn-18bf2.firebaseapp.com',
    storageBucket: 'pingolearn-18bf2.appspot.com',
  );
}
